spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/littlell/config-server.git
          username: littlell
          password: 88688142
server:
  port: 4001