cas:
  host: https://account.glodon.com
  filter:
    processing:
      path: j_spring_cas_security_check
service:
  host: http://127.0.0.1:5002/internal-api
  key: 9j7p95yBTBnTKRHJpeeu8913K2nlQuRD
  secret: tHnb8zYi6P1e5jtFdE4D8EXEbL97tD0U
server:
  port: 6001
security:
    success:
        path: http://127.0.0.1:5002/internal-api/cas/return
spring:
    session:
        store-type: redis
    redis:
        database: 0
        #host: 10.129.57.84
        host: 127.0.0.1
        password:
        port: 6379
